[workspace]
resolver = "2"

members = ["firmware", "service", "shared"]

[workspace.package]
edition = "2024"
license = "MIT"
version = "0.1.0"

[profile.dev.package.aerosmart-firmware]
debug = true
opt-level = "z"
incremental = true

[profile.release.package.aerosmart-firmware]
debug = false
opt-level = "z"
incremental = true

[profile.dev]
lto = true

[profile.release]
lto = true
