[workspace]
resolver = "2"

members = ["firmware", "service", "shared", "panel/src-tauri"]

[workspace.package]
edition = "2024"
license = "MIT"
version = "0.1.0"

[profile.dev.package.asfirmware]
debug       = true
opt-level   = "z"
incremental = true

[profile.release.package.asfirmware]
debug       = false
opt-level   = "z"
incremental = true

[profile.dev]
lto = true

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
opt-level = 3
