[package]
name = "panel"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow = "1.0.100"
axum = "0.8.8"
juniper = "0.17.0"
reqwest = "0.13.1"
rmcp = { version = "0.12.0", features = ["server"] }
serde = { version = "1.0.228", features = ["derive"] }
sqlx = { version = "0.8.6", features = ["postgres"] }
tokio = { version = "1.49.0", features = ["full"] }
