// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LidarData = { distance_cm: number; signal_strength: number; time_elapsed_ms: bigint }
