// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnalogPressureSensorData = {
  pressures_pa: [number, number, number, number]
  /**
   * Bitmask indicating which channels had valid data
   * - Bit 7: Channel 1
   * - Bit 6: Channel 2
   * - Bit 5: Channel 3
   * - Bit 4: Channel 4
   * - Bit 3-0: Reserved (should be 0)
   */
  valid_bitmask: number
  time_elapsed_ms: bigint
}
