// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BatteryData = { voltage_v: number, soc_percent: number, time_elapsed_ms: bigint, };
