// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImuData = {
  accel_z: number
  gyro_x: number
  gyro_y: number
  quad_w: number
  quad_i: number
  quad_j: number
  quad_k: number
  time_elapsed_ms: bigint
}
