// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImuVibrationMetrics = {
  rms_vibration: number
  dominant_frequency_hz: number
  peak_magnitude: number
  time_elapsed_ms: bigint
}
