// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PitotAirspeedData = { splitter_left: number, splitter_right: number, static_port: number, time_elapsed_ms: bigint, };
