// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QeiData = {
  position_counts: number
  /**
   * true = upcounting, false = downcounting
   */
  direction: boolean
  pressed: boolean
  time_elapsed_ms: bigint
}
